export const en = {
  'Daily record': 'Record daily water intake and track',
  'Water tracker': 'Water consumption tracker',
  'Register user': 'Try tracker',
  'Login user': 'Sign In',
  'Habit drive': 'Habit drive',
  'View statistics': 'View statistics',
  'Personal rate': ' Personal rate setting',
  'Our 1': 'Our',
  'Our 2': 'customers',
  'Happy customers': 'happy',
  'Sign in': 'Sign in',
  'Do not': 'Don`t have an account?',
  'Register user form': 'Sign up',
  'Email user': 'Email',
  'Password user': 'Password',
  'Enter email': 'Enter your email',
  'Enter password': 'Enter your password',
  'Already have': 'Already have an account?',
  'Repeat password': 'Repeat password',
  'Count water': 'L',
  'Daily norma': 'My daily norma',
  'Today water': 'Today',
  'Add water': 'Add water',
  'Hello user': 'Hello',
  'Water add': 'ml',
  'Month water': 'Month',
  'Month january': 'January',
  'Month february': 'February',
  'Month march': 'March',
  'Month april': 'April',
  'Month may': 'May',
  'Month june': 'June',
  'Month july': 'July',
  'Month august': 'August',
  'Month september': 'September',
  'Month october': 'October',
  'Month november': 'November',
  'Month december': 'December',
};
